[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name="cell_type_mapper"
version="1.4.0rc"
dependencies = [
    "anndata",
    "argschema",
    "matplotlib",
    "marshmallow==3.12.2",
    "numpy",
    "pytest",
    "scipy"
]
requires-python = ">=3.8"
authors = [
    {name = "Scott Daniel", email = "scott.daniel@alleninstitue.org"},
]
